//This file is automatically generated

// consumer-controller

import { ConsumerController } from '@controller';
export default {
    actions: {
        [ConsumerController.feign.method] : {
            summary: 'feign',
            method: 'get',
            url: (payload) => `/basic/test/hello`,
            parameters: [],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
