//This file is automatically generated

// depart-index-controller

import { DepartIndexController } from '@controller';
export default {
    actions: {
        [DepartIndexController.addDepartIndex.method] : {
            summary: '部门指标录入',
            method: 'post',
            url: (payload) => `/basic/deptindex`,
            parameters: [{'in':'body','name':'departIndexVO','description':'departIndexVO','required':true,'schema':{'$ref':'#/definitions/部门指标VO'}}],
        },
        [DepartIndexController.deleteDepartIndexByIds.method] : {
            summary: '部门指标删除(多选框)',
            method: 'post',
            url: (payload) => `/basic/deptindex/deletelist`,
            parameters: [{'in':'body','name':'deleteParam','description':'deleteParam','required':true,'schema':{'$ref':'#/definitions/DeleteParam'}}],
        },
        [DepartIndexController.searchDepartIndex.method] : {
            summary: '部门指标查询',
            method: 'post',
            url: (payload) => `/basic/deptindex/search`,
            parameters: [{'in':'body','name':'departIndexSearchParam','description':'部门ID,年份','required':false,'schema':{'$ref':'#/definitions/部门指标查询'}}],
        },
        [DepartIndexController.updateDepartIndex.method] : {
            summary: '部门指标修改',
            method: 'put',
            url: (payload) => `/basic/deptindex/update`,
            parameters: [{'in':'body','name':'updateParam','description':'部门指标ID,部门指标数值','required':true,'schema':{'$ref':'#/definitions/部门指标修改参数'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
