//This file is automatically generated

// sys-notification-controller

import { SysNotificationController } from '@controller';
export default {
    actions: {
        [SysNotificationController.addNotice.method] : {
            summary: '系统公告添加',
            method: 'post',
            url: (payload) => `/basic/sysnotification`,
            parameters: [{'in':'body','name':'sysNotificationVO','description':'sysNotificationVO','required':true,'schema':{'$ref':'#/definitions/系统公告管理VO'}}],
        },
        [SysNotificationController.configUEditor.method] : {
            summary: '处理关于ueditor插件相关的请求',
            method: 'get',
            url: (payload) => `/basic/sysnotification/configUEditor`,
            parameters: [{'name':'action','in':'query','description':'action','required':false,'type':'string'}],
        },
        [SysNotificationController.deleteNoticeByIds.method] : {
            summary: '系统公告删除(多选框)',
            method: 'post',
            url: (payload) => `/basic/sysnotification/deletelist`,
            parameters: [{'in':'body','name':'deleteParam','description':'deleteParam','required':true,'schema':{'$ref':'#/definitions/DeleteParam'}}],
        },
        [SysNotificationController.readNotice.method] : {
            summary: '阅读公告,阅读数+1',
            method: 'post',
            url: (payload) => `/basic/read/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [SysNotificationController.searchNotice.method] : {
            summary: '系统公告分页查询',
            method: 'post',
            url: (payload) => `/basic/sysnotification/search`,
            parameters: [{'in':'body','name':'searchParam','description':'searchParam','required':true,'schema':{'$ref':'#/definitions/系统公告查询条件'}}],
        },
        [SysNotificationController.updateNotice.method] : {
            summary: '系统公告修改',
            method: 'put',
            url: (payload) => `/basic/sysnotification/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'in':'body','name':'sysNotificationVO','description':'sysNotificationVO','required':true,'schema':{'$ref':'#/definitions/系统公告管理VO'}}],
        },
        [SysNotificationController.uploadImage.method] : {
            summary: '处理关于ueditor插件相关的请求',
            method: 'post',
            url: (payload) => `/basic/sysnotification/configUEditor`,
            parameters: [{'name':'action','in':'query','description':'action','required':false,'type':'string'},{'name':'upfile','in':'formData','description':'upfile','required':false,'type':'file'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
