//This file is automatically generated

// watch-card-mark-controller

import { WatchCardMarkController } from '@controller';
export default {
    actions: {
        [WatchCardMarkController.addCollectionCard.method] : {
            summary: '收藏所选观察卡',
            method: 'post',
            url: (payload) => `/basic/watchcardmark/addCollectionCard`,
            parameters: [{'in':'body','name':'参数:观察卡编号数组集、收藏者id、权限id（非必填）','description':'addCollectionCardParam','required':true,'schema':{'$ref':'#/definitions/收藏观察卡参数'}}],
        },
        [WatchCardMarkController.addExcellentCard.method] : {
            summary: '标记优秀观察卡',
            method: 'post',
            url: (payload) => `/basic/watchcardmark/addExcellentCard`,
            parameters: [{'in':'body','name':'参数：观察卡编号数组集、创建人、所属部门','description':'addExcellentCardParam','required':true,'schema':{'$ref':'#/definitions/标记优秀观察卡参数'}}],
        },
        [WatchCardMarkController.cancelCollectionCard.method] : {
            summary: '取消收藏观察卡',
            method: 'post',
            url: (payload) => `/basic/watchcardmark/cancelCollectionCard`,
            parameters: [{'in':'body','name':'deleteParam','description':'deleteParam','required':true,'schema':{'$ref':'#/definitions/DeleteParam'}}],
        },
        [WatchCardMarkController.cancelSignCard.method] : {
            summary: '取消标记观察卡',
            method: 'delete',
            url: (payload) => `/basic/watchcardmark/cancelSign/${payload.cardId}`,
            parameters: [{'name':'cardId','in':'path','description':'cardId','required':true,'type':'string'}],
        },
        [WatchCardMarkController.exportMyMarkCard.method] : {
            summary: '导出我标记的优秀观察卡',
            method: 'post',
            url: (payload) => `/basic/watchcardmark/exportMyMarkCard`,
            parameters: [{'in':'body','name':'exportParam','description':'exportParam','required':true,'schema':{'$ref':'#/definitions/CardMarkExportParam'}}],
        },
        [WatchCardMarkController.findMyMarkCard.method] : {
            summary: '查询我的标记优秀观察卡列表',
            method: 'post',
            url: (payload) => `/basic/watchcardmark/findMyMarkCard`,
            parameters: [{'in':'body','name':'myMarkCardParam','description':'myMarkCardParam','required':false,'schema':{'$ref':'#/definitions/查询我的优秀标记参数'}}],
        },
        [WatchCardMarkController.searchExcellentCard.method] : {
            summary: '优秀观察卡录入-查询优秀观察卡列表',
            method: 'post',
            url: (payload) => `/basic/watchcardmark/queryExcellentCard`,
            parameters: [{'in':'body','name':'查询条件(所属部门、观察时间、录入时间、被观察区域)','description':'searchExcellectCardParam','required':false,'schema':{'$ref':'#/definitions/查询优秀观察卡条件参数'}}],
        },
        [WatchCardMarkController.searchMyCollection.method] : {
            summary: '查看我的收藏夹',
            method: 'post',
            url: (payload) => `/basic/watchcardmark/queryMyCollectionList`,
            parameters: [{'in':'body','name':'参数：用户ID(必填）、录入时间、观察区域等查询条件','description':'searchMyCollectionParam','required':true,'schema':{'$ref':'#/definitions/查询我的收藏夹检索条件'}}],
        },
        [WatchCardMarkController.searchUnMarkCard.method] : {
            summary: '查询未标记观察卡列表',
            method: 'post',
            url: (payload) => `/basic/watchcardmark/queryUnMarkCardList`,
            parameters: [{'in':'body','name':'查询条件(所属部门、观察时间、录入时间、被观察区域、仅查询自己的观察卡时，登陆用户id)','description':'searchUnMarkCardParam','required':false,'schema':{'$ref':'#/definitions/查询未标记观察卡条件参数'}}],
        },
        [WatchCardMarkController.searchUpperLimit.method] : {
            summary: '查询当前季度优秀观察卡标记上限',
            method: 'post',
            url: (payload) => `/basic/watchcardmark/searchUpperLimit`,
            parameters: [{'name':'deptId','in':'query','description':'deptId','required':true,'type':'string'}],
        },
        [WatchCardMarkController.updateExcellentCard.method] : {
            summary: '优秀观察卡录入-填写邮寄地址后保存',
            method: 'post',
            url: (payload) => `/basic/watchcardmark/updateExcellentCard`,
            parameters: [{'in':'body','name':'参数：优秀观察卡编号、邮寄地址、登录者ID','description':'updateExcellentCardParam','required':true,'schema':{'$ref':'#/definitions/优秀观察卡更新参数'}}],
        },
        [WatchCardMarkController.updateUpperLimit.method] : {
            summary: '更新当前季度优秀观察卡标记上限 ',
            method: 'post',
            url: (payload) => `/basic/watchcardmark/updateUpperLimit`,
            parameters: [{'in':'body','name':'参数：主键ID,当前用户ID、上限值','description':'updateUpperLimitParam','required':true,'schema':{'$ref':'#/definitions/优��观察卡查询条件VO'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
