//This file is automatically generated

// watch-card-controller

import { WatchCardController } from '@controller';
export default {
    actions: {
        [WatchCardController.addWatchCard.method] : {
            summary: '观察卡录入',
            method: 'post',
            url: (payload) => `/basic/watchcard`,
            parameters: [{'in':'body','name':'watchCardVO','description':'watchCardVO','required':true,'schema':{'$ref':'#/definitions/观察卡VO'}}],
        },
        [WatchCardController.deleteWatchCardByIds.method] : {
            summary: '观察卡刪除(多选框)',
            method: 'post',
            url: (payload) => `/basic/watchcard/deletelist`,
            parameters: [{'in':'body','name':'deleteParam','description':'deleteParam','required':true,'schema':{'$ref':'#/definitions/DeleteParam'}}],
        },
        [WatchCardController.findWatchCardById.method] : {
            summary: '根据ID查询观察卡',
            method: 'get',
            url: (payload) => `/basic/watchcard/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
        [WatchCardController.getCardCountByObserver.method] : {
            summary: '根据观察者获取观察卡数量',
            method: 'post',
            url: (payload) => `/basic/watchcard/observer/count`,
            parameters: [{'in':'body','name':'searchParam','description':'searchParam','required':true,'schema':{'$ref':'#/definitions/查询未标记观察卡条件参数'}}],
        },
        [WatchCardController.getCardRecord.method] : {
            summary: '获取观察卡录入回显信息',
            method: 'get',
            url: (payload) => `/basic/watchcard/record/${payload.userId}`,
            parameters: [{'name':'userId','in':'path','description':'userId','required':true,'type':'string'}],
        },
        [WatchCardController.importExcel.method] : {
            summary: '观察卡Excel导入',
            method: 'post',
            url: (payload) => `/basic/watchcard/excel/import`,
            parameters: [{'name':'file','in':'formData','description':'file','required':true,'type':'array','items':{'type':'file'},'collectionFormat':'multi'}],
        },
        [WatchCardController.searchWatchCard.method] : {
            summary: '观察卡模糊查询',
            method: 'post',
            url: (payload) => `/basic/watchcard/search`,
            parameters: [{'in':'body','name':'watchCardSearchParam','description':'部门ID,观察者姓名,观察时间,创建时间,观察地点,来源','required':false,'schema':{'$ref':'#/definitions/观察卡查询'}}],
        },
        [WatchCardController.updateWatchCard.method] : {
            summary: '根据ID编辑观察卡',
            method: 'put',
            url: (payload) => `/basic/watchcard/update/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'in':'body','name':'watchCardVO','description':'watchCardVO','required':true,'schema':{'$ref':'#/definitions/观察卡VO'}}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
