//This file is automatically generated

// watch-card-mark-notice-controller

import { WatchCardMarkNoticeController } from '@controller';
export default {
    actions: {
        [WatchCardMarkNoticeController.getNoticeCountByUserId.method] : {
            summary: '获取通知个数',
            method: 'get',
            url: (payload) => `/basic/notice/count/${payload.userId}`,
            parameters: [{'name':'userId','in':'path','description':'userId','required':true,'type':'string'}],
        },
        [WatchCardMarkNoticeController.getNoticeListByUserId.method] : {
            summary: '获取通知列表',
            method: 'get',
            url: (payload) => `/basic/notice/list/${payload.userId}`,
            parameters: [{'name':'userId','in':'path','description':'userId','required':true,'type':'string'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
