//This file is automatically generated

// dict-entry-controller

import { DictEntryController } from '@controller';
export default {
    actions: {
        [DictEntryController.create.method] : {
            summary: '新增',
            method: 'post',
            url: (payload) => `/api/dict-entries`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'$ref':'#/definitions/DictEntry'}}],
        },
        [DictEntryController.deleteByIds.method] : {
            summary: '按主键集合(以&#x27;,&#x27;分割)删除',
            method: 'delete',
            url: (payload) => `/api/dict-entries/${payload.ids}`,
            parameters: [{'name':'ids','in':'path','description':'ids','required':true,'type':'string'}],
        },
        [DictEntryController.findByCodeAndTypeCode.method] : {
            summary: '根据字典Code和字典类型查找',
            method: 'get',
            url: (payload) => `/api/dict-entries/rewrite/byCodeAndTypeCode`,
            parameters: [{'name':'dictCode','in':'query','description':'dictCode','required':false,'type':'string'},{'name':'dictTypeCode','in':'query','description':'dictTypeCode','required':false,'type':'string'}],
        },
        [DictEntryController.findByCriteria.method] : {
            summary: '分页查询字典项',
            method: 'get',
            url: (payload) => `/api/dict-entries/page-search`,
            parameters: [{'name':'code','in':'query','description':'编码','required':false,'type':'string'},{'name':'dictTypeCode','in':'query','required':false,'type':'string'},{'name':'dictTypeId','in':'query','required':false,'type':'string'},{'name':'dictTypeName','in':'query','required':false,'type':'string'},{'name':'id','in':'query','description':'Id','required':false,'type':'string'},{'name':'listRoot','in':'query','description':'是否只查询顶层数据','required':false,'type':'boolean'},{'name':'loadChildren','in':'query','description':'是否加载子节点','required':false,'type':'boolean'},{'name':'loadChildrenLevel','in':'query','description':'从当前层开始，需要加载子节点的层级','required':false,'type':'integer','format':'int32'},{'name':'loadOthers','in':'query','description':'是否加载节点的其它资源','required':false,'type':'boolean'},{'name':'locale','in':'query','required':false,'type':'string'},{'name':'name','in':'query','description':'名称','required':false,'type':'string'},{'name':'pageNum','in':'query','required':false,'type':'integer','format':'int32'},{'name':'pageSize','in':'query','required':false,'type':'integer','format':'int32'},{'name':'parentId','in':'query','description':'父对象的id','required':false,'type':'string'},{'name':'status','in':'query','required':false,'type':'string'},{'name':'usingLikeQuery','in':'query','description':'是否使用模糊查询','required':false,'type':'boolean'}],
        },
        [DictEntryController.findById.method] : {
            summary: '按主键查询',
            method: 'get',
            url: (payload) => `/api/dict-entries/${payload.id}`,
            parameters: [{'name':'id','in':'path','description':'id','required':true,'type':'string'},{'name':'loadChildren','in':'query','description':'loadChildren','required':false,'type':'boolean'},{'name':'loadLevel','in':'query','description':'loadLevel','required':false,'type':'integer','default':0,'format':'int32'},{'name':'locale','in':'query','description':'locale','required':false,'type':'string'}],
        },
        [DictEntryController.findByNameAndTypeCode.method] : {
            summary: '根据字典名称和字典类型查找',
            method: 'get',
            url: (payload) => `/api/dict-entries/rewrite/byNameAndTypeCode`,
            parameters: [{'name':'dictName','in':'query','description':'dictName','required':false,'type':'string'},{'name':'dictTypeCode','in':'query','description':'dictTypeCode','required':false,'type':'string'}],
        },
        [DictEntryController.findDictTree.method] : {
            summary: '获取指定字典类型树形结构',
            method: 'post',
            url: (payload) => `/api/dict-entries/rewrite/tree`,
            parameters: [{'in':'body','name':'searchParam','description':'字典类型Code,父级字典Code','required':false,'schema':{'$ref':'#/definitions/字典树型展示'}}],
        },
        [DictEntryController.findSecondDictByCodeAndTypeCode.method] : {
            summary: '根据根据字典Code和字典类型获取二级字典项',
            method: 'get',
            url: (payload) => `/api/dict-entries/rewrite/second/byCodeAndTypeCode`,
            parameters: [{'name':'dictCode','in':'query','description':'dictCode','required':false,'type':'string'},{'name':'dictTypeCode','in':'query','description':'dictTypeCode','required':false,'type':'string'}],
        },
        [DictEntryController.findSecondList.method] : {
            summary: '获取二级字典项',
            method: 'get',
            url: (payload) => `/api/dict-entries/rewrite/secondlist`,
            parameters: [{'name':'dictTypeCode','in':'query','description':'字典类型Code','required':false,'type':'string','allowEmptyValue':false}],
        },
        [DictEntryController.update.method] : {
            summary: '更新',
            method: 'put',
            url: (payload) => `/api/dict-entries`,
            parameters: [{'in':'body','name':'model','description':'model','required':true,'schema':{'$ref':'#/definitions/DictEntry'}}],
        },
        [DictEntryController.updateDict.method] : {
            summary: '字典修改',
            method: 'put',
            url: (payload) => `/api/dict-entries/rewrite/${payload.id}`,
            parameters: [{'in':'body','name':'DictChildren','description':'DictChildren','required':true,'schema':{'$ref':'#/definitions/部门树型展示'}},{'name':'id','in':'path','description':'id','required':true,'type':'string'}],
        },
    },
    // state: {},
    // mutations: {},
    // getters: {}
}
